name: Tests

on: [pull_request]

jobs:

  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
        
      - name: Setup
        id: setup
        uses: prefecthq/actions-setup-nodejs@chore/enable-workflow

      - name: Lint application
        run: |
          npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup
        id: setup
        uses: prefecthq/actions-setup-nodejs@chore/enable-workflow

      - name: Build package
        run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup
        id: setup
        uses: prefecthq/actions-setup-nodejs@chore/enable-workflow

      - name: Run tests
        run: npm run test